"""initial foundation

Revision ID: ed36863c3869
Revises: 
Create Date: 2026-06-01 11:24:12.384282
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ed36863c3869'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_actor', 'audit_logs', ['actor_type', 'actor_id'], unique=False)
    op.create_index('ix_audit_logs_company_created', 'audit_logs', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('legal_name', sa.Text(), nullable=False),
    sa.Column('trade_license_number', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'CANCELLED', name='company_status'), server_default='PENDING', nullable=False),
    sa.Column('subscription_status', postgresql.ENUM('TRIAL', 'ACTIVE', 'PAST_DUE', 'CANCELLED', name='subscription_status'), server_default='TRIAL', nullable=False),
    sa.Column('primary_admin_email', sa.String(length=320), nullable=False),
    sa.Column('created_by_platform_admin', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('company_admins',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('totp_secret', sa.String(length=255), nullable=True),
    sa.Column('role', postgresql.ENUM('COMPANY_OWNER', 'COMPANY_ADMIN', 'COMPANY_VIEWER', name='company_role'), server_default='COMPANY_ADMIN', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='fk_company_admins_company', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'email', name='uq_company_admins_company_email')
    )
    op.create_index(op.f('ix_company_admins_company_id'), 'company_admins', ['company_id'], unique=False)
    op.create_table('company_branding',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('logo_object_key', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=9), nullable=True),
    sa.Column('secondary_color', sa.String(length=9), nullable=True),
    sa.Column('welcome_text', sa.Text(), nullable=True),
    sa.Column('support_email', sa.String(length=320), nullable=True),
    sa.Column('locale_default', sa.String(length=5), server_default='en', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('company_settings',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('reminder_offsets_days', postgresql.ARRAY(sa.Integer()), server_default=sa.text("'{3,7,14}'"), nullable=False),
    sa.Column('overdue_after_days', sa.Integer(), server_default=sa.text('21'), nullable=False),
    sa.Column('auto_reminders_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('weekly_summary_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('retention_months', sa.Integer(), server_default=sa.text('24'), nullable=False),
    sa.Column('enabled_cert_types', postgresql.ARRAY(sa.String()), server_default=sa.text("'{VAT,CT}'"), nullable=False),
    sa.Column('group_cert_policy', postgresql.ENUM('REJECT', 'WARN', name='group_cert_policy'), server_default='REJECT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_settings')
    op.drop_table('company_branding')
    op.drop_index(op.f('ix_company_admins_company_id'), table_name='company_admins')
    op.drop_table('company_admins')
    op.drop_table('companies')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_company_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
    # Drop enum types (autogenerate does not remove these).
    op.execute("DROP TYPE IF EXISTS group_cert_policy")
    op.execute("DROP TYPE IF EXISTS company_role")
    op.execute("DROP TYPE IF EXISTS subscription_status")
    op.execute("DROP TYPE IF EXISTS company_status")
